

export const people = [
    {vorname: "Finja", nachname: "Abbenseth", nummer: 314},
    {vorname: "Narmin", nachname: "Abdullayeva", nummer: 356},
    {vorname: "Yassine", nachname: "Allouba", nummer: 475},
    {vorname: "Andrea", nachname: "Antonazzo", nummer: 466},
    {vorname: "Maximillian", nachname: "Barthelmey", nummer: 374},
    {vorname: "Yullia", nachname: "Bashtova", nummer: 364},
    {vorname: "Özgen", nachname: "Baybutoglu", nummer: 371},
    {vorname: "David", nachname: "Bents", nummer: 316},
    {vorname: "Elisabeth Sophie", nachname: "Berg", nummer: 341},
    {vorname: "Mats", nachname: "Brase", nummer: 354},
    {vorname: "Friederike", nachname: "Brathe", nummer: 427},
    {vorname: "Valerie", nachname: "Bris Moreno", nummer: 462},
    {vorname: "Lorenz", nachname: "Budnik", nummer: 325},
    {vorname: "Jan", nachname: "Buehne", nummer: 360},
    {vorname: "Ferhat", nachname: "Bulut", nummer: 493},
    {vorname: "Damian", nachname: "Ciachorowski", nummer: 473},
    {vorname: "Hilal", nachname: "Cubukcu", nummer: 332},
    {vorname: "Franziska", nachname: "Cyrkel", nummer: 494},
    {vorname: "Mellissa Regina", nachname: "Da Silva Guimaraes", nummer: 361},
    {vorname: "Lucas", nachname: "del Valle Steimer", nummer: 353},
    {vorname: "Alexej-Johannes", nachname: "Dierßen", nummer: 482},
    {vorname: "Linda", nachname: "Duske", nummer: 343},
    {vorname: "Lea", nachname: "Epperlein", nummer: 401},
    {vorname: "Chris Julian", nachname: "Erdmann", nummer: 381},
    {vorname: "Fenja", nachname: "Fecht", nummer: 304},
    {vorname: "Vanessa", nachname: "Forchheim", nummer: 333},
    {vorname: "Carolin", nachname: "Fortwengel", nummer: 313},
    {vorname: "Johannes", nachname: "Fraatz", nummer: 416},
    {vorname: "Raphael", nachname: "Fütterer", nummer: 380},
    {vorname: "Erik Walter Julian", nachname: "Gehle", nummer: 342},
    {vorname: "Sophie", nachname: "Germann", nummer: 390},
    {vorname: "Tobias", nachname: "Germer", nummer: 384},
    {vorname: "Janne Henrike", nachname: "Geschke", nummer: 331},
    {vorname: "Anastasiia", nachname: "Grinkina", nummer: 457},
    {vorname: "Vanessa", nachname: "Groeneveld", nummer: 412},
    {vorname: "Leon", nachname: "Groothuis", nummer: 424},
    {vorname: "Fabienne", nachname: "Großstück", nummer: 426},
    {vorname: "Maik", nachname: "Gudi", nummer: 326},
    {vorname: "Feriel", nachname: "Guelbi", nummer: 405},
    {vorname: "Christine", nachname: "Haetinger", nummer: 803},
    {vorname: "Anna", nachname: "Hafenberg", nummer: 404},
    {vorname: "Ahmad", nachname: "Harb", nummer: 372},
    {vorname: "Adrian", nachname: "Hartmann", nummer: 373},
    {vorname: "Adelind", nachname: "Herbig", nummer: 805},
    {vorname: "Morgan", nachname: "Higgins", nummer: 465},
    {vorname: "Sarah Katharina", nachname: "Hooss", nummer: 453},
    {vorname: "Heiko", nachname: "Huber", nummer: 446},
    {vorname: "Niklas", nachname: "Hüneburg", nummer: 443},
    {vorname: "Paula Marie", nachname: "Jacobs", nummer: 471},
    {vorname: "Michelle", nachname: "Käckenmeister", nummer: 374},
    {vorname: "Serdar", nachname: "Kahraman", nummer: 422},
    {vorname: "Luisa", nachname: "Klingenstein", nummer: 346},
    {vorname: "Sema", nachname: "Kondakci", nummer: 403},
    {vorname: "Yannik", nachname: "Krautz", nummer: 484},
    {vorname: "Ellen", nachname: "Krone", nummer: 345},
    {vorname: "Jonas", nachname: "Kupfernagel", nummer: 301},
    {vorname: "Leonie Ariadne", nachname: "Kutschke", nummer: 431},
    {vorname: "Levi", nachname: "Lehne", nummer: 441},
    {vorname: "Charleen", nachname: "Löbenberg", nummer: 417},
    {vorname: "Sarah", nachname: "Loehr", nummer: 425},
    {vorname: "Pia", nachname: "Ludwig", nummer: 802},
    {vorname: "Paula", nachname: "Lüke", nummer: 335},
    {vorname: "Viktor", nachname: "Lynok", nummer: 434},
    {vorname: "David", nachname: "Maack", nummer: 303},
    {vorname: "Gayane", nachname: "Manukyan", nummer: 402},
    {vorname: "Linda Almée", nachname: "Markus", nummer: 432},
    {vorname: "Yanina", nachname: "Markus", nummer: 363},
    {vorname: "Daniel", nachname: "Meißner", nummer: 322},
    {vorname: "Paulina", nachname: "Menzel", nummer: 474},
    {vorname: "Joel", nachname: "Metz", nummer: 801},
    {vorname: "Sebastian", nachname: "Meyerhoff", nummer: 492},
    {vorname: "Lina", nachname: "Migge", nummer: 472},
    {vorname: "Lukas", nachname: "Müller", nummer: 370},
    {vorname: "Vera", nachname: "Nannen", nummer: 336},
    {vorname: "Henri", nachname: "Oertel", nummer: 330},
    {vorname: "Victoria", nachname: "Ohnimus", nummer: 355},
    {vorname: "Lena", nachname: "Oliver", nummer: 311},
    {vorname: "Vanessa", nachname: "Paul", nummer: 392},
    {vorname: "Leanna", nachname: "Penner", nummer: 454},
    {vorname: "Carina", nachname: "Peters", nummer: 495},
    {vorname: "Maxim", nachname: "Paffenrot", nummer: 414},
    {vorname: "Vanessa Yissel", nachname: "Picalua Parra", nummer: 461},
    {vorname: "Maurice", nachname: "Plogmeyer", nummer: 444},
    {vorname: "Till", nachname: "Preuß", nummer: 421},
    {vorname: "Jan", nachname: "Przyklenk", nummer: 310},
    {vorname: "Killian", nachname: "Rathske", nummer: 302},
    {vorname: "Tom", nachname: "Rauschenberger", nummer: 315},
    {vorname: "Maryna", nachname: "Redka", nummer: 365},
    {vorname: "Ann-Kathrin", nachname: "Rehbeck", nummer: 447},
    {vorname: "Vibeke", nachname: "Rehbeck", nummer: 455},
    {vorname: "Dana", nachname: "Rinteln", nummer: 411},
    {vorname: "Ebru Nur", nachname: "Sahin", nummer: 340},
    {vorname: "Abderrahim", nachname: "Sbihi", nummer: 300},
    {vorname: "Anna-Lena", nachname: "Schaller", nummer: 483},
    {vorname: "Leon", nachname: "Schellewald", nummer: 442},
    {vorname: "Tom-Moritz", nachname: "Schindler", nummer: 481},
    {vorname: "Elizabeth", nachname: "Schmidt", nummer: 350},
    {vorname: "Mika", nachname: "Schneider", nummer: 320},
    {vorname: "Patrick", nachname: "Schrandt", nummer: 393},
    {vorname: "Jakob", nachname: "Schulz", nummer: 423},
    {vorname: "Laetitia", nachname: "Schulz", nummer: 435},
    {vorname: "Alisa", nachname: "Schütte", nummer: 491},
    {vorname: "Valentin", nachname: "Seidl", nummer: 456},
    {vorname: "Moritz", nachname: "Severit", nummer: 383},
    {vorname: "Iulia", nachname: "Sokolova", nummer: 485},
    {vorname: "Giuseppina", nachname: "Solombrino", nummer: 464},
    {vorname: "Malte", nachname: "Sparenborg", nummer: 451},
    {vorname: "Maximillian", nachname: "Stähr", nummer: 323},
    {vorname: "Florian", nachname: "Stratmann", nummer: 312},
    {vorname: "Finn", nachname: "Sünkler", nummer: 391},
    {vorname: "Judith", nachname: "Tangerding", nummer: 334},
    {vorname: "Daniel", nachname: "Tauberger", nummer: 321},
    {vorname: "Ali", nachname: "Tavafi", nummer: 366},
    {vorname: "Lisa", nachname: "Thoms", nummer: 437},
    {vorname: "Bennet", nachname: "Tönsfeldt", nummer: 324},
    {vorname: "Alejandro", nachname: "Torres Zayas", nummer: 467},
    {vorname: "Sophie", nachname: "Touati", nummer: 351},
    {vorname: "Magdalena", nachname: "Treiber", nummer: 344},
    {vorname: "Loredana", nachname: "Tripari", nummer: 452},
    {vorname: "Elisa", nachname: "van Elten", nummer: 413},
    {vorname: "Boyan Blagoev", nachname: "Velev", nummer: 436},
    {vorname: "Emilia", nachname: "Weiher", nummer: 415},
    {vorname: "Ole", nachname: "Wilts", nummer: 394},
    {vorname: "Adrian", nachname: "Wojtaszewski", nummer: 382},
    {vorname: "Felix", nachname: "Zierz", nummer: 445},
    {vorname: "Emilia", nachname: "Ziomber", nummer: 433},
];
